# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ buildGoModule, fetchFromGitHub }:

buildGoModule rec {
  name = "hostess-${version}";
  version = "0.5.2";

  # nix-prefetch-url --unpack https://github.com/cbednarski/hostess/archive/v0.5.2.tar.gz
  src = fetchFromGitHub {
    owner = "cbednarski";
    repo = "hostess";
    rev = "v${version}";
    sha256 = "1izszf60nsa6pyxx3kd8qdrz3h47ylm17r9hzh9wk37f61pmm42j";
  };

  vendorSha256 = null;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = { };
}
