# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# ZFS Setup
# sudo mkswap -Lswap /dev/sda4
# sudo mkswap -Lswap2 /dev/sdb4
# sudo swapon /dev/sda4
# sudo swapon /dev/sdb4
# sudo mkfs.vfat -F32 -n boot /dev/sda3
# sudo mkfs.vfat -F32 -n boot2 /dev/sdb3
# zpool create -O mountpoint=none -O atime=off -O compression=on -O xattr=sa -O acltype=posixacl -o ashift=12 -R /mnt rpool mirror /dev/sda1 /dev/sdb1
# zfs create -o mountpoint=none rpool/local
# zfs create -o mountpoint=legacy rpool/local/nix
# zfs create -o mountpoint=none rpool/system
# zfs create -o mountpoint=none rpool/user
# zfs create -o mountpoint=legacy rpool/system/root
# zfs create -o mountpoint=legacy rpool/system/var
# zfs create -o mountpoint=legacy rpool/user/dotfiles
# zfs create -o mountpoint=legacy rpool/user/home
# mkdir /tmp/dotfiles
# sudo chown -R nixos:users /tmp/dotfiles
# sudo mount -t zfs rpool/user/dotfiles /tmp/dotfiles
# rsync -avPhz --delete-after --delete-excluded --exclude '.direnv' $HOME/.dotfiles/ nixos@some-ip:/tmp/dotfiles/
# mount -t zfs rpool/system/root /mnt
# cd /mnt
# sudo mkdir boot home nix var
# mount -t zfs rpool/local/nix /mnt/nix
# mount -t zfs rpool/user/home /mnt/home
# mount -t zfs rpool/system/var /mnt/var
# cd /tmp/dotfiles/
# nix-shell -p nixFlakes
# sudo nixos-install --flake .#yggdrasil
{ lib, modulesPath, ... }: {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [ "elevator=none" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "rpool/system/root";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "rpool/user/home";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "rpool/local/nix";
    fsType = "zfs";
  };

  fileSystems."/var" = {
    device = "rpool/system/var";
    fsType = "zfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0157-F0D7";
    fsType = "vfat";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/11ac9e4f-fc80-4141-a06a-8badb709b4e7"; }
    { device = "/dev/disk/by-uuid/60a5bc5a-6359-400b-8299-933aae4fef0f"; }
  ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
