" Generated by vim-plug
" Sat 26 Jun 2021 08:45:53 PM CDT
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['asyncomplete-lsp.vim'].commit = '684c34453db9dcbed5dbf4769aaa6521530a23e0'
silent! let g:plugs['elixir-snippets'].commit = '1bc7619f9cb87ab8472ce32437b4cb00888581c8'
silent! let g:plugs['grep.vim'].commit = '852ddb0c6590bbc41c508d7f5d2fc17112492def'
silent! let g:plugs['vim-bootstrap-updater'].commit = '4ac51cd33bed21797da82c245746bb0bd993f28a'
silent! let g:plugs['vim-coloresque'].commit = 'e12a5007068e74c8ffe5b1da91c25989de9c2081'
silent! let g:plugs['vim-css3-syntax'].commit = '82afdcdc634fb013821026de8720895854108ad7'
silent! let g:plugs['vim-nerdtree-tabs'].commit = '07d19f0299762669c6f93fbadb8249da6ba9de62'
silent! let g:plugs['vim-session'].commit = '9e9a6088f0554f6940c19889d0b2a8f39d13f2bb'
silent! let g:plugs['vimerl'].commit = '536f7e265449b2609d217da4193f2e4060e6b728'
silent! let g:plugs['vimproc.vim'].commit = '8f40d86ab938d5df8c1c9824320621ae9f0d5609'

PlugUpdate!

